[build-system]
requires = ["setuptools>=64.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "propofol"
version = "0.4.0"
authors = [
  { name="Richard Bartels", email="r.t.bartels-6@umcutrecht.nl" },
  { name="Luke van Boven", email="L.vanBoven@umcutrecht.nl" },
  { name="Jona Joachim", email="j.a.joachim@umcg.nl" },
]
description = "Development of the model for the dose decision-support tool of propofol."
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies =[
  "dash>=4.1.0",
  "numpy~=2.2",
  "pandas~=2.2",
  "plotly>=6.6.0",
  "scipy~=1.15",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.2",
    "pytest>=8.0.1",
    "matplotlib~=3.10",
    "nbstripout>=0.7.1",
    "pytest-cov>=5.0.0",
    "rsconnect-python>=1.24.0",
]
lint = [
    "ruff>=0.7.1",
]

[tool.uv]
default-groups = ["dev", "lint"]

[tool.ruff]
src = ["src"]
line-length = 100

[tool.ruff.lint]
select = [
    "B",    # flake8-bugbear
    "E",    # pycodestyle errors
    "W",    # pycodestyle warnings
    "F",    # pyflakes
    "C90",  # mccabe complexity
    "I",    # isort
    "ERA",  # Eradicate (commented out code)
    "A",    # flake8-builtins (overwriting python builtins)
    "PTH",  # flake8-use-pathlib
    "N",    # pep8-naming
    "D101", # pydocstyle: Missing docstring in class
    "D102", # pydocstyle: Missing docstring in method
    "D103", # pydocstyle: Missing docstring in function
]

[tool.ruff.lint.pep8-naming]
ignore-names = [
    "X",  # Allow the use of X as variable in scikit-learn
    # Allow capitals similar to use in pkpd literature
    # As PEP 20 says, "Readability counts" (also pep8 "know when to be inconsistent")
    "MAP*", "RMAP",  # Allow the use of MAP (mean arterial pressure) as there is a build-in map function
    "A0", "A1", "A2", "A3",
    "Cp*", "Ce*",
    "V1", "V2", "V3",
    "E50",
    "*dotA*", "*dotC*",
]

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = ["D101", "D102", "D103"] # Allow unit tests without docstring
